server:
  port: 8080
spring:
  profiles:
    active: dev

  #配置请求参数
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写
  #配置数据库
  datasource:
    url: jdbc:mysql://${sqlData.url}:3306/dacuan?characterEncoding=UTF-8&&serverTimezone=GMT&&allowMultiQueries=true&&&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: ${sqlData.username}
    password: ${sqlData.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis云服务器
  redis:
    host: ${myRedis.host}
    port: ${myRedis.port}
    password: ${myRedis.password}
    database: ${myRedis.database}
  #mongodb
  data:
    mongodb:
      authentication-database: ${myMongodb.authentication-database}
      host: ${myMongodb.host}
      port: ${myMongodb.port}
      database: ${myMongodb.database}
      username: ${myMongodb.username}
      password: ${myMongodb.password}
#配置mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
